services:
  api:
    image: unifyops-core:${ENV:-local}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/unifyops
      - PYTHONPATH=/app
      - CORS_ALLOW_ORIGINS=http://localhost:5174
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOW_HEADERS=Content-Type,Authorization
      - SECRET_KEY=your_super_secret_key_for_development_only_change_in_production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unifyops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
