version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-$(date +%Y%m%d%H%M%S)}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app
    env_file:
      - .env.local
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - API_RELOAD=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/unifyops
      - PYTHONPATH=/app
    command: ./scripts/start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unifyops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
