version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-$(date +%Y%m%d%H%M%S)}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app
    env_file:
      - .env.local
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - API_RELOAD=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
