"""create_initial_schema

Revision ID: d72117ff249c
Revises: 
Create Date: 2025-04-10 01:42:25.171861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd72117ff249c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('rule_definition', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('cloud_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['app_schema.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['app_schema.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('terraform_dir', sa.String(length=255), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['app_schema.organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['app_schema.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('initiated_by', sa.String(length=255), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['app_schema.environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('environment_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['app_schema.environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_path', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['app_schema.environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('state_management',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('backend_type', sa.String(length=50), nullable=False),
    sa.Column('state_location', sa.String(length=255), nullable=False),
    sa.Column('lock_id', sa.String(length=255), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['app_schema.environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['app_schema.resources.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['app_schema.resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.drop_table('connections')
    op.drop_index('ix_resources_environment_id', table_name='resources')
    op.drop_index('ix_resources_name', table_name='resources')
    op.drop_index('ix_resources_resource_type', table_name='resources')
    op.drop_table('resources')
    op.drop_table('state_management')
    op.drop_table('deployments')
    op.drop_table('environment_versions')
    op.drop_table('cloud_credentials')
    op.drop_table('teams')
    op.drop_index('ix_environments_name', table_name='environments')
    op.drop_table('environments')
    op.drop_table('organizations')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('module_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auto_apply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('init_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('plan_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('apply_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name='resources_environment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resources_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_resources_resource_type', 'resources', ['resource_type'], unique=False)
    op.create_index('ix_resources_name', 'resources', ['name'], unique=False)
    op.create_index('ix_resources_environment_id', 'resources', ['environment_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('organizations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('environments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('module_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auto_apply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('init_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('plan_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('apply_execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('global_variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='environments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_environments_name', 'environments', ['name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='teams_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey')
    )
    op.create_table('cloud_credentials',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='cloud_credentials_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cloud_credentials_pkey')
    )
    op.create_table('environment_versions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name='environment_versions_environment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='environment_versions_pkey')
    )
    op.create_table('deployments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name='deployments_environment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deployments_pkey')
    )
    op.create_table('state_management',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('backend_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('state_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name='state_management_environment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='state_management_pkey')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rule_definition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='compliance_rules_pkey')
    )
    op.create_table('connections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('connection_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['resources.id'], name='connections_source_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['resources.id'], name='connections_target_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='connections_pkey')
    )
    op.drop_table('connections', schema='app_schema')
    op.drop_table('state_management', schema='app_schema')
    op.drop_table('resources', schema='app_schema')
    op.drop_table('environment_versions', schema='app_schema')
    op.drop_table('deployments', schema='app_schema')
    op.drop_table('environments', schema='app_schema')
    op.drop_table('teams', schema='app_schema')
    op.drop_table('cloud_credentials', schema='app_schema')
    op.drop_table('organizations', schema='app_schema')
    op.drop_table('compliance_rules', schema='app_schema')
    # ### end Alembic commands ### 